services :
  spark :
    image: apache/spark:4.0.1
    hostname: apache-spark
    ports :
      - "7077:7077"   # Spark master port
      - "8080:8080"   # Spark master web UI
      - "8081:8081"   # Spark worker web UI
      - "15002:15002" # Spark Connect server port
      - "4040:4040"   # Spark Connect web UI
    command: >
      bash -c "/opt/spark/sbin/start-master.sh; /opt/spark/sbin/start-connect-server.sh; /opt/spark/sbin/start-worker.sh spark://192.168.1.7:7077; sleep infinity"