[project]
name = "spark-lab"
version = "0.1.0+dev"
description = "Labs for learning Apache Spark"
readme = "README.md"
requires-python = ">=3.10, <3.11"
dependencies = [
  "jupyter>=1.1.1",
  "pandas>=2.3.2",
  "pyspark-client==4.0.1",
]
